language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev"
  # - "nightly"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
# need to run the command once before testing
before_script: romspam
# command to run tests
script: nosetests
